baseURL = "https://dgalizzi.github.io/"
languageCode = "en-us"
title = "/home/dgalizzi"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "trac"
    tabWidth = 4

[params]
	highlight = true

[module]
	[[module.imports]]
		path = "github.com/dgalizzi/etch"
